mc:
  container_name: mc
  image: itzg/minecraft-server:java17-alpine
  ports:
    - '25565:25565'
  environment:
    EULA: 'true'
    OVERRIDE_SERVER_PROPERTIES: 'true'
    TYPE: FABRIC
    VERSION: '1.20.2' # Must be string sometimes
    MODRINTH_PROJECTS: fabric-api:0.89.3+1.20.2,owo-lib:0.11.4+1.20.2,server-portals
    #MODRINTH_PROJECTS: fabric-api,owo-lib,server-portals
    REMOVE_OLD_MODS: 'true'
  volumes:
    - './data/:/data/'
    #- '../build/libs/:/mods/'
    - '/etc/timezone:/etc/timezone:ro'
  tty: true
  restart: always
