name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  # For any reason, specifying this in the modrinth step does not work?
  # But it is also well documented here, so this should be ok to do
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag condition
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "Ref is a tag"

      - name: Check out project
        if: success()
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        if: success()
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'microsoft'

      - name: Setup Gradle
        if: success()
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3

      - name: Build v1.19
        if: success()
        run: gradle remapJar -Pv=1.19

      - name: Build v1.19.1
        if: success()
        run: gradle remapJar -Pv=1.19.1

      - name: Build v1.19.2
        if: success()
        run: gradle remapJar -Pv=1.19.2

      - name: Build v1.19.3
        if: success()
        run: gradle remapJar -Pv=1.19.3

      - name: Build v1.19.4
        if: success()
        run: gradle remapJar -Pv=1.19.4

      - name: Build v1.20
        if: success()
        run: gradle remapJar -Pv=1.20

      - name: Build v1.20.1
        if: success()
        run: gradle remapJar -Pv=1.20.1

      - name: Build v1.20.2
        if: success()
        run: gradle remapJar -Pv=1.20.2

      - name: Release on GitHub
        if: success() && startsWith(github.ref, 'refs/tags/') # Failsafe check again
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/libs/server-portals-*.jar
            README.md
            CHANGELOG.md
            LICENSE
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          fail_on_unmatched_files: true

      - name: Upload to modrinth v1.19
        if: success()
        run: gradle modrinth -Pv=1.19

      - name: Upload to modrinth v1.19.1
        if: success()
        run: gradle modrinth -Pv=1.19.1

      - name: Upload to modrinth v1.19.2
        if: success()
        run: gradle modrinth -Pv=1.19.2

      - name: Upload to modrinth v1.19.3
        if: success()
        run: gradle modrinth -Pv=1.19.3

      - name: Upload to modrinth v1.19.4
        if: success()
        run: gradle modrinth -Pv=1.19.4

      - name: Upload to modrinth v1.20
        if: success()
        run: gradle modrinth -Pv=1.20

      - name: Upload to modrinth v1.20.1
        if: success()
        run: gradle modrinth -Pv=1.20.1

      - name: Upload to modrinth v1.20.2
        if: success()
        run: gradle modrinth -Pv=1.20.2
